### PR TITLE
Introduce SSL Parameter Configuration

### PR DESCRIPTION
**Pull request by 4quarks**
Implemented an SSL parameter configuration feature, allowing users to specify SSL settings in the pdnssoccli.yml configuration file. This enhancement enables the use of self-signed certificates without SSL verification failures. Users can configure the SSL parameter accordingly to accommodate various SSL certificate setups, ensuring seamless integration with different environments.

### CODE REVIEW

**Comment by arvchristos** [comment]
Thank you for the contribution @4quarks ! :tada: 

I suggest the following prior to merging this:
* Could you please also update the sample config file at https://github.com/CERN-CERT/pdnssoc-cli/blob/main/config.yml.sample with the newly introduced config option?
* If the change affects configuration, please do not forget to cross link MRs between pdnssoc and pdnssoc-cli . I can see that you also created https://github.com/CERN-CERT/pDNSSOC/pull/24 which I will append to the MR description
* Please also update the following files in the same MR (https://github.com/CERN-CERT/pDNSSOC/pull/24):  
    * https://github.com/CERN-CERT/pDNSSOC/blob/main/files/configuration/pdnssoccli/pdnssoccli.yml
    * https://github.com/CERN-CERT/pDNSSOC/blob/main/files/docker/pdnssoccli.yml

In the meantime, I will add this to the next release as it is a new configuration parameter.

**Comment by 4quarks** [comment]
Done!

**Comment by arvchristos** [comment]
> Done!

Thank you. However, I see that the last step is not pushed. Could you please also update the following files with the new parameter?

 * https://github.com/CERN-CERT/pDNSSOC/blob/main/files/configuration/pdnssoccli/pdnssoccli.yml
 * https://github.com/CERN-CERT/pDNSSOC/blob/main/files/docker/pdnssoccli.yml

**Comment by 4quarks** [comment]
Done

**Review by arvchristos — APPROVED** [review]

**Pull request merged**
